/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeaderNav: typeof import('./components/AppHeaderNav/AppHeaderNav.vue')['default']
    AppHeaderSticky: typeof import('./components/AppHeaderSticky/AppHeaderSticky.vue')['default']
    HeaderSticky: typeof import('./components/HeaderSticky/HeaderSticky.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
