/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeaderCart: typeof import('./components/AppHeaderCart/AppHeaderCart.vue')['default']
    AppHeaderNav: typeof import('./components/AppHeaderNav/AppHeaderNav.vue')['default']
    AppHeaderSticky: typeof import('./components/AppHeaderSticky/AppHeaderSticky.vue')['default']
    Bread: typeof import('./components/XtxUI/Bread/index.vue')['default']
    Button: typeof import('./components/XtxUI/Button/index.vue')['default']
    CheckBox: typeof import('./components/XtxUI/CheckBox/index.vue')['default']
    City: typeof import('./components/XtxUI/City/index.vue')['default']
    Count: typeof import('./components/XtxUI/Count/index.vue')['default']
    Dialog: typeof import('./components/XtxUI/Dialog/index.vue')['default']
    HeaderSticky: typeof import('./components/HeaderSticky/HeaderSticky.vue')['default']
    HomePanel: typeof import('./components/HomePanel/HomePanel.vue')['default']
    ImageView: typeof import('./components/XtxUI/ImageView/index.vue')['default']
    InfiniteLoad: typeof import('./components/XtxUI/InfiniteLoad/index.vue')['default']
    Item: typeof import('./components/XtxUI/Bread/Item.vue')['default']
    Message: typeof import('./components/XtxUI/Message/index.vue')['default']
    More: typeof import('./components/XtxUI/More/index.vue')['default']
    Pane: typeof import('./components/XtxUI/Tabs/pane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./components/XtxUI/Skeleton/Skeleton.vue')['default']
    Sku: typeof import('./components/XtxUI/Sku/index.vue')['default']
    Slider: typeof import('./components/XtxUI/Slider/index.vue')['default']
    Tabs: typeof import('./components/XtxUI/Tabs/index.vue')['default']
  }
}
